FROM python:3.13.2-alpine

# Set working directory
WORKDIR /app

# Install poetry
RUN pip install poetry==1.8.4

# Disable virtual environments in Poetry
RUN poetry config virtualenvs.create false

# Copy just the dependency files first
COPY pyproject.toml poetry.lock /app/

COPY . .

ENV VIRTUAL_ENV=/app/.venv \
  PATH="/app/.venv/bin:$PATH"
# Install dependencies
RUN poetry install --no-dev

# Copy the rest of the code

# Command to run the application


