name: Deploy Cron & API Stack

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_DIR: apps/senpy-ai-news-report
  IMAGE_NAME: senpy-ai-news-report
  IMAGE_TAG: ${{ github.sha }}
  IMAGE_NAMESPACE: ${{ github.repository_owner }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push container images
        working-directory: ${{ env.PROJECT_DIR }}
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_NAMESPACE: ${{ env.IMAGE_NAMESPACE }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          set -euo pipefail

          IMAGE_NAME_VALUE="${IMAGE_NAME:-}"
          IMAGE_NAMESPACE_VALUE="${IMAGE_NAMESPACE:-}"
          IMAGE_TAG_VALUE="${IMAGE_TAG:-latest}"

          if [ -z "${IMAGE_NAME_VALUE}" ]; then
            echo "IMAGE_NAME is not set." >&2
            exit 1
          fi

          if [ -z "${IMAGE_NAMESPACE_VALUE}" ]; then
            echo "IMAGE_NAMESPACE is not set." >&2
            exit 1
          fi

          OWNER_LOWER=$(printf '%s' "${IMAGE_NAMESPACE_VALUE}" | tr '[:upper:]' '[:lower:]')
          IMAGE_REPO="ghcr.io/${OWNER_LOWER}/${IMAGE_NAME_VALUE}"
          IMAGE_SHA="${IMAGE_REPO}:${IMAGE_TAG_VALUE}"
          IMAGE_LATEST="${IMAGE_REPO}:latest"

          docker build -f Dockerfile.cron -t "${IMAGE_SHA}" .
          docker tag "${IMAGE_SHA}" "${IMAGE_LATEST}"
          docker push "${IMAGE_SHA}"
          docker push "${IMAGE_LATEST}"

          echo "IMAGE_REPO=${IMAGE_REPO}" >> "$GITHUB_ENV"

      - name: Deploy on remote host
        uses: appleboy/ssh-action@v1.0.3
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_NAMESPACE: ${{ env.IMAGE_NAMESPACE }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
          API_HOST_PORT: ${{ secrets.API_HOST_PORT }}
        with:
          host: ${{ secrets.CRON_DEPLOY_HOST }}
          username: ${{ secrets.CRON_DEPLOY_USER }}
          key: ${{ secrets.CRON_DEPLOY_SSH_KEY }}
          script: |
            set -euo pipefail

            IMAGE_NAME_VALUE="${IMAGE_NAME:-}"
            IMAGE_NAMESPACE_VALUE="${IMAGE_NAMESPACE:-}"
            IMAGE_TAG_VALUE="${IMAGE_TAG:-latest}"

            if [ -z "${IMAGE_NAME_VALUE}" ]; then
              echo "IMAGE_NAME is not set." >&2
              exit 1
            fi

            if [ -z "${IMAGE_NAMESPACE_VALUE}" ]; then
              echo "IMAGE_NAMESPACE is not set." >&2
              exit 1
            fi

            OWNER_LOWER=$(printf '%s' "${IMAGE_NAMESPACE_VALUE}" | tr '[:upper:]' '[:lower:]')
            IMAGE_REPO="ghcr.io/${OWNER_LOWER}/${IMAGE_NAME_VALUE}"
            IMAGE_REF="${IMAGE_REPO}:${IMAGE_TAG_VALUE}"

            if [ -n "${GHCR_USERNAME:-}" ] && [ -n "${GHCR_TOKEN:-}" ]; then
              echo "${GHCR_TOKEN}" | docker login ghcr.io -u "${GHCR_USERNAME}" --password-stdin
            else
              echo 'Warning: GHCR credentials not provided; attempting to pull using existing auth context.' >&2
            fi

            if ! docker pull "${IMAGE_REF}"; then
              echo "Falling back to latest image tag" >&2
              docker pull "${IMAGE_REPO}:latest"
              IMAGE_REF="${IMAGE_REPO}:latest"
            fi

            for svc in cron-github cron-feeds api; do
              docker rm -f "${svc}" >/dev/null 2>&1 || true
            done

            TARGET_DIR="${{ secrets.CRON_DEPLOY_PATH }}"
            ENV_FILE="${TARGET_DIR}/.env"

            if [ ! -f "${ENV_FILE}" ]; then
              echo 'Warning: .env file not found on remote host; containers may fail to start.' >&2
            fi

            ENV_ARG=""
            if [ -f "${ENV_FILE}" ]; then
              ENV_ARG="--env-file ${ENV_FILE}"
            fi
            #
            # docker run -d \
            #   --name cron-github \
            #   --restart unless-stopped \
            #   ${ENV_ARG} \
            #   "${IMAGE_REF}" \
            #   poetry run python -m crons.github_trends_cron
            #
            # docker run -d \
            #   --name cron-feeds \
            #   --restart unless-stopped \
            #   ${ENV_ARG} \
            #   "${IMAGE_REF}" \
            #   poetry run python -m crons.feeds_cron

            API_PORT="${API_HOST_PORT:-8000}"

            docker run -d \
              --name api \
              --restart unless-stopped \
              ${ENV_ARG} \
              -p "${API_PORT}:8000" \
              "${IMAGE_REF}" \
              poetry run uvicorn senpy_ai_news_report.main:app --host 0.0.0.0 --port 8000
